### PR TITLE
Expand values exposed to the template

### PR DESCRIPTION
**Pull request by charliek**
Exposed data structure passed to the template is richer so it now allows the following values to be used in the template:

```
{{.ID}}
{{.Service}}
{{.Tags}}
{{.Port}}
{{.IP}}
{{.Node}}
{{.}}
```

The default `{{.}}` value remains the same so this change will be backwards compatible. One could also simulate the default using the below values in the template string `server {{.Node}}_{{.ID}} {{.IP}}:{{.Port}}`.

This should allow this project to be used for nginx templates and also allow haproxy values like cookie name be set if needed.

### CODE REVIEW

**Comment by armon** [comment]
I'm going to hold off on this, as I think this is rather HAProxy specific, and we need to start molding this to be a more generic `consul-template` instead.

**Comment by charliek** [comment]
What do you envision consul-template looking like? I'm happy to make changes if desired, but it sounds like you have bigger changes in mind.

**Comment by armon** [comment]
Not sure yet. Need to figure out a way to expose at least the KV stuff nicely, and various endpoint data from the catalog. Haven't thought about it too much yet.

**Comment by charliek** [comment]
Would you be interested in keeping the "ServerEntry" struct to allow for finer grained server details to be pulled out in the template, and remove the cookie name function altogether? This should allow the project to be used for things like nginx I believe, and wouldn't be haproxy specific. 

Otherwise we can close this PR for now in favor of bigger `consul-template` changes to come.

**Comment by armon** [comment]
@charliek Yeah that does sound like a good idea! Let's separate that out and merge that piece in.

**Comment by charliek** [comment]
@armon I've updated the code as discussed, and update the PR description to match.

**Comment by armon** [comment]
LGTM! Thanks!

**Pull request merged**
